### PR TITLE
Added Cygwin termcap and terminfo packages to fix backspace issues

### PR DESCRIPTION
**Pull request by rasa**
Added Cygwin termcap and terminfo packages to fix backspace issues
Removed "SSHD" from 'netsh' command as it reported a syntax error (see screenshot)
Symlinked /home/vagrant to %SystemDrive%/users/vagrant (missing in some configs)
Corrected product key in misheska-win2012x64/floppy/Autounattend.xml
Standardized install-cygwin-sshd.bat across all windows builds
Added win7x64pro template
All Windows builds have been tested, and install unattendedly using VMWare WS 10

### CODE REVIEW

**Comment by rasa** [comment]
Syntax error in netsh command:

**Comment by misheska** [comment]
Rebased in & pushed into trunk.  Seems to work better.  I can backspace over "vagrant ssh" with abandon!

**Comment by rasa** [comment]
Thanks for merging this. For some reason, my previous PR did not show up in https://github.com/misheska/basebox-packer/graphs/contributors , but this one does. 

Is it OK to deleted PRs #5 and #6 now?

**Comment by rasa** [comment]
@misheska I'd really like to see https://github.com/rasa/basebox-packer/tree/add-termcap-and-terminfo/template/misheska-win7x64pro pulled in as well, as I would prefer not to maintain a separate fork. What are your thoughts on this? Thanks.

**Comment by misheska** [comment]
I probably got your e-mail address wrong on the first rebase in...

**Comment by misheska** [comment]
I try to make sure that my basebox definitions are trunk stable, so I
throughly review and test submissions before pushing.  For the professional
template, I want to edit the Autounattend.xml article accordingingly
http://misheska.com/blog/2013/07/26/windows-7-automated-install-settings/and
prepare/vet every setting.  I need more time to review, but I'll
definitely push a vetted professional template.  (Right now, any extra time
I have is spent working on 8.1 / 2012 R2 templates, so I will probably
finish those first, then circle back and test the professional one).

**Comment by rasa** [comment]
Gotcha. Thanks. I've tried several times to get 8.1 and 2012 R2 to build without pausing, but so far, no go. Both 8.1, and 2012 R2 show the same error: 
2012 R2 additionally pauses here:

**Comment by StefanScherer** [comment]
I have built a working basebox for 8.1 preview and commited into my fork https://github.com/StefanScherer/basebox-packer/tree/master/template/stefan-win81x64preview
I am new to Git and it is difficult for me to make a pull request because I have changed a lot in my master branch. But I'm willing to learn to do this in the next days or weeks.
This basebox is then working with vagrant with winrm (vagrant-windows), but I had to do extra steps making winrm work, because windows still resists to use a public network although there are two entries in autounattend.xml that should set it to "work network". I don't know if there is a cleaner way to do this.

I also tried to create a 2012 R2 preview basebox with the operating system strings as used in 2012 (without the R2), as you can see at https://github.com/StefanScherer/basebox-packer/tree/master/template/stefan-win2012R2x64preview. But cygwin then crashes while installing. But I haven't tried your latest install-cygwin-sshd.bat script yet.

Regards
Stefan﻿

Am 01. Oktober 2013 um 03:07 schrieb Ross Smith II notifications@github.com:

**Comment by misheska** [comment]
Awesome Stefan, can't wait to look at what you've done!  It's probably worth looking at Ross Smith has done to improve the Cygwin install to see if it addresses your cygwin crashing issue.

**Comment by rasa** [comment]
@StefanScherer: Also try hardcoding `ARCH` via

```
if "%PROCESSOR_ARCHITECTURE%" == "AMD64" (set ARCH=x86_64) else (set ARCH=x86)
set ARCH=x86
set URL=http://cygwin.com/setup-%ARCH%.exe
```

as the `x86_64` version of setup crashed many times for me, but the `x86` never crashed.

**Comment by StefanScherer** [comment]
@rasa: Thank you, this trick works fine on 2012 R2, using the 32bit version of Cygwin.

**Comment by misheska** [comment]
I figured out how to get baseboxes created for Windows 8.1 gold & Windows 2012 R2 gold.  Key was adding scsi0.virtualDev = "lsisas1068" to the .vmx file, as it doesn't work with the default lsilogic driver vagrant inserts by default.  I will be posting Windows 8.1 & Windows 2012 R2 gold templates later this evening or sometime tomorrow.

**Comment by rasa** [comment]
That's great news. How did you stumble on that gem?

**Comment by misheska** [comment]
Well, after I had wasted a ton of time trying every possible permutation of DiskSettings, I thought of trying to install with an Autoattend.xml in a VM by hand without using any automation.  It worked.  So then I interpreted the error message literally that it couldn't find the disk, and compared .vmx files between the working VM and the one packer generates and narrowed it down to the SCSI driver.  Easy in retrospect ;-)

**Comment by misheska** [comment]
Pushed Windows 8.1 Enterprise, Windows 8.1 Professional and Windows 2012 R2 templates

**Pull request closed without merging**
