### PR TITLE
Added net install packer config and new ks.cfg file for centos 5.10

### PR DESCRIPTION
**Pull request by elliott-davis**
Added a new config for centos 5.10 and new KS file.  Tested on VMWare.

### CODE REVIEW

**Comment by misheska** [comment]
P.S. In a kickstart the "url" directive takes precedence over the "cdrom" directive, so it doesn't hurt for it to be there.  I frequently leave both in so I can just comment out the url directives when I want to flip to using DVD media.

**Comment by elliott-davis** [comment]
Sounds good to me.  I looked over the changes and they look fine for my use case as well (albeit I do enjoy having headless mode set to true for troubleshooting).  I'm going to go ahead and close this PR and will open a new one with the remaining centos net installs.

**Comment by misheska** [comment]
I missed the headless mode setting - what are you referring to exactly?  Anything that helps troubleshooting I don't mind adding.

**Comment by elliott-davis** [comment]
In the json file you can set "headless":true and it'll open up a vnc connection to the box during the install process.  I can leave it in for this round of commits if you want to pull it and test it out.  I'm almost done with the work on the centos net install boxes.

**Comment by misheska** [comment]
I didn't know about that one.  Sounds like a good improvement.  Leave it in
and I'll try it out.  Apologies for missing that setting.

**Comment by elliott-davis** [comment]
Just a quick question before I push.  When I do a packer build on my box it typically always fails because the path doesn't exist for the box.  Changing the path fixes it but I am curious if you just have a dir set up for each OS that the final build goes to.  That is the best explanation I could think of.

**Comment by misheska** [comment]
I use the Makefile to build the boxes.  It creates the virtualbox/vmware
output directories automatically.  With so many boxes, it's not practical
for me to cd into each directory individually - the Makefile helps me to be
able to have a Jenkins box spinning looking for box changes using the
Makefile as an integral component (as well as doing box verification).
 (And having one place for the box out is easier than having to look within
each directory - and since I name the virtualbox/vmware boxes the same, I
need a way to distinguish between the two without needing to crack the box
open to look at the metadata.json file)

That being said, the Makefile doesn't currently work ;-)  I still need to
update it to work with the recent directory structure changes.  I hope to
get some time this weekend to update that.

**Pull request closed without merging**
