### PR TITLE
Compact and defrag Windows baseboxes, fixes #63

### LINKED ISSUE #63: Compact and defrag Windows baseboxes
Good tip: https://github.com/joefitzgerald/packer-windows/pull/53  Because Windows defrag.exe can't be used usefully in a script, using ultradefrag instead, plus Sysinternals sdelete tool to zero free disk space

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by rasa** [comment]
Dang it. Only the windows7 builds will work, as I should have 

```
for i in windows* ; do cp windows7/script/vmtools.bat $i/script ; done
```

Pushing an update now. Can you remerge, or do I have to create a new PR?

**Comment by misheska** [comment]
Sure, I can remerge (not that big of a deal - I rushed it as I’m moving the templates to box-cutter…once the Jenkins boxes are live, everything will go through a build pipeline)….

**Comment by misheska** [comment]
P.S. In box-cutter, putting windows templates in a single directory in one repo, so you will no longer have to copy scripts twelve times ;-)

**Comment by rasa** [comment]
Thank the Maker! :)

**Pull request merged**
