### PR TITLE
Fixes #35: Use of Powershell in preinstall scripts stymies slipstreaming

### LINKED ISSUE #35: Use of Powershell in preinstall scripts stymies Windows update slipstreamg
Use wget or bitsadmin, if found in the PATH, or on A:\, otherwise use powershell
Skip downloading any file if it's found on a:\, d:\ or in the PATH
This addresses the following issues after slipstreaming Windows updates into installation media:
  After installing all Windows and .Net 3.51 updates, running powershell during installation would produce:
    "Version v4.0.30319 of the .NET Framework is not installed and it is required to run version 3 of Windows PowerShell."
  After installing all Windows and .Net 3.51 updates, and then .NET 4.51 (NDP451-KB2858728-x86-x64-AllOS-ENU.exe),
  running powershell during installation would produce:
    "Internal Windows PowerShell error.  Loading managed Windows PowerShell failed with error 80070002."

### PR DESCRIPTION
**Pull request by rasa**
- Skip all .bat/.cmd scripts that start with an underscore (floppy/00-run-all-scripts.cmd)
- Added debug variables PACKER_DEBUG and PACKER_PAUSE (floppy/00-run-all-scripts.cmd)
- Moved A:\ to end of the PATH, to give precendence to installed applications (floppy/00-run-all-scripts.cmd)
- Search for tee.exe in the PATH first, before looking in A:\ (floppy/00-run-all-scripts.cmd)
- Removed extra " char in junction command (floppy/openssh.bat)
- Replace IF with GOTO to avoid delayed expansion issues, and to easily add future provisioners (script/provisioner.bat)
- Replace all ! with % as appropriate
- Use wget or bitsadmin, if found in the PATH, or on A:\, otherwise use powershell
- Skip downloading any file if it's found on a:\, d:\ or in the PATH
- Replaced `choice` with the built-in `timeout` command, as it's simpler
- This addresses the following issues after slipstreaming Windows updates into installation media:
  After installing all Windows and .Net 3.51 updates, running powershell during installation would produce:
  "Version v4.0.30319 of the .NET Framework is not installed and it is required to run version 3 of Windows PowerShell."
  After installing all Windows and .Net 3.51 updates, and then .NET 4.51 (NDP451-KB2858728-x86-x64-AllOS-ENU.exe),
  running powershell during installation would produce:
  "Internal Windows PowerShell error. Loading managed Windows PowerShell failed with error 80070002."

Testing and working in VMWare 10 on all builds but:
- win2012-standard-cygwin (ssh doesn't start)
- win2012r2-standard-cygwin (ssh doesn't start)

### CODE REVIEW

**Comment by misheska** [comment]
I can reproduce the win2012-standard-cygwin & win2012-standard-cygwin not starting ssh as well.  I don't like this and am taking at look at it further.  So far, I cant tell that it is never started because the script doesn't detect the SSH service being installed - investigating further.

**Comment by rasa** [comment]
Yeah, I looked into it a bit this time, but quickly gave up as openssh works. BTW, the openssh installer is now up to 6.6p1-1. See http://www.mls-software.com/opensshd.html . I can submit a PR if you want.

**Comment by rasa** [comment]
Added
- Replaced `choice` with the built-in `timeout` command, as it's simpler

to the PR description.

**Comment by misheska** [comment]
Issue seems to be fixed with Cygwin 1.7.29

**Comment by rasa** [comment]
Thanks for merging. as I know it's a bit hacky. One thing I didn't mention in the changelog, is this PR give us the ability now to do a completely "offline" installation, as `_download.cmd` looks to see if a file already exists (on floppy, or CD), before downloading it.

**Comment by misheska** [comment]
Thanks for the note.  I saw that.  I’ll add that to the README section on Windows.

It’s evolving, not hacky ;-)  This is new territory.  It can be refined.  I’m happy to see you’re also keeping up with what Joe Fitzgerald is doing in his templates.  Packer is extremely weak in the logging and testing department.  I’m happy to see how you’re experimenting with retrofitting this in (similar to how I’m experimenting with vagrant-serverspec for testing).  And I understand that everyone is still wrapping their arms around how to do patch/updates management in Packer images - and in Windows, this is particularly complex.

Mitchell claims that a Chef provisioner is coming to Packer soon - if that’s the case, I am in a position to help make sure that a lot of the heavy lifting for all these things could be done with Chef (which would be ideal for most of these things - as it should be able to get around the Powershell upgrading issue…though that could be handled with an intermediate script as well.)  Keep on keeping on.  Your work is appreciated.

**Comment by misheska** [comment]
It also looks like there are some good changes afoot for Windows in Vagrant 1.6 which might change things significantly in the Windows templates - http://www.vagrantup.com/blog/feature-preview-vagrant-1-6-windows.html  Shawn Neal & Paul Morton contributed changes to get vagrant-windows moved into the vagrant core (shouldn't change the templates, but a good thing for it to finally be standard).  WinRM will be supported, so there can be non-SSH templates (and if Vagrant supports all these things, Test Kitchen gets them for free as well, for Chef).

**Pull request merged**
