### PR TITLE
Cygwin setup 2.830 properly handles dependencies now (version 2)

### PR DESCRIPTION
**Pull request by rasa**
Changelog:
- Removed package dependencies, as Cygwin setup 2.830 no longer requires them to be listed.
- Changed mirror to http://mirrors.kernel.org/sourceware/cygwin/ for speed.
- Replaced hardcoded C: drive references with %SYSTEMDRIVE%.
- Hardcoded architecture to "x86" as "x86_64" seems a bit buggy still.
- Changed temporary directory from C:\WINDOWS\temp to %TEMP%.
- Added additional comments

I tested these changes, and the boxes

```
win2008r2-datacenter
win2008r2-enterprise
win2008r2-standard
win2008r2-web
win7x64-enterprise
win7x64-pro
win7x86-enterprise
win7x86-pro
win81x64-enterprise
win81x64-pro
win8x64-enterprise
win8x86-enterprise
```

successfully install OpenSSH, and VMWare Tools.

The boxes

```
win2012-datacenter
win2012-standard
win2012r2-datacenter
win2012r2-standard
```

_sometimes_ fail to build, as the sshd service logs the following error when it's started:

`sshd pid service sshd failed signal 11 raised`

### CODE REVIEW

**Comment by misheska** [comment]
I'm taking a look at https://github.com/joefitzgerald/packer-windows as well - he's got some good ideas for modernizing the install some more (in addition to the good work you've done!)

**Comment by rasa** [comment]
`OpenSSH for Windows` is an interesting solution, and one worth looking into. Here's my initial take on its strengths and weaknesses:

Strengths:
1. Single file installer. No external downloads or dependencies
2. Original OpenSSH code
3. Source code of installer is available
4. Actively maintained
5. GPL License

Weaknesses:
1. A "hard-coded" Cygwin installation of just the `openssh` package
2. Other Cygwin packages do not come pre-installed (for example, no `wget`, I'm not sure how they would be added, but I'm sure it's possible)
3. Must wait for a new installer to receive updates
4. Updating does not preserve configuration file changes (I'm assuming, I haven't tested)
5. OpenSSH and Cygwin cannot be installed on the same system, at the same time (as the Installer checks for this, I haven't tested this).
6. Installs in `C:\Program Files` by default. The space in the directory name may be problematic for Cygwin programs, and bash files. This can be overridden by the installer (I think it's `/D=c:\cygwin`)

I would say that if you're looking for a quick way to ssh into a Windows box, this is a great option. If you want a more true, and extensible, Linux-like environment to run complex provisioning scripts in bash, it may not be the best solution.

**Comment by misheska** [comment]
Thanks for the feedback.  Yes, my plan is to retain the Cygwin (for now) & use your extensible version.  Just combining the best bits of your work and his work.  What I liked the most is that he has a great solution for the postinstall32/64.bat conundrum - use a .BAT script, which can accurately detect the CPU bitted-ness ;-)

I’ll post a new version, hopefully today in one of the Windows flavours - if you have time I would appreciate some more feedback.

**Comment by misheska** [comment]
OK, I just took a stab on collecting together your's and Joe's suggested improvements in this commit:
https://github.com/misheska/basebox-packer/commit/235c0f401698ddbd6ab0605e173df285dd7f58c3

I hardcoded the Windows 2012/2012r2 boxes to use the 64-bit version of Cygwin, as I find it unacceptable to ever get that `sshd pid service sshd failed signal 11 raised` error after going through all the trouble of trying to build the basebox (and for me, it seemed to happen more frequently than "sometimes" _sigh_)

Another interesting issue with Windows 2012/2012r2 was that the %ProgramFiles% environment variable isn't defined in the shell provided to the install_cygwin script.

If you have time, please review and provide feedback.  I want to know what you think.

**Comment by rasa** [comment]
Everything packaged fine, without issues.

**Pull request closed without merging**
