### PR TITLE
Fixed cygwin installation issues, other niceties

### PR DESCRIPTION
**Pull request by rasa**
Changed http://www.cygwin.com/setup.exe to http://www.cygwin.com/setup-x86_64.exe (as http://www.cygwin.com/setup.exe is 404 now)

Explicitly list all cygwin dependencies, as they do not appear to install automatically any more
Symlinked /home/vagrant to %SystemDrive%/users/vagrant
Removed "SSHD" from 'netsh' command as it reported a syntax error
Changed hardcoded C: values to use %SystemDrive%
Fixed other minor cygwin installation issues
Changed iso_urls to be relative in template.json
Updated 'make list' output to display in sorted order
Corrected product key in misheska-win2012x64/floppy/Autounattend.xml
Added removal of template/*/output-vmware directories to 'clean' action in Makefile
Added win7x64pro template
All Windows builds have been tested, and install unattendedly using VMWare WS 10

### CODE REVIEW

**Comment by rasa** [comment]
Here's an example of the dependency issues using the original `install-cygwin-sshd.bat` script:

**Comment by rasa** [comment]
@misheska: Are you _sure_ it's `../../../` and not `../../`, as packer is running in the `template/misheska-xxx/` directory, which is only two directories away from the directory that `iso/` is in? I'm on Windows, and they both work, but that may not be the case in OSX, or Linux.

**Comment by misheska** [comment]
Yes, I'm testing on OSX & Linux, and no you can't use the file:// specifier with a relative path.  Would you please test the relative path on Windows with the "file://" specifier to see if it works on Windows as well?  That would be ideal as then it would work on all three platforms...

**Comment by misheska** [comment]
P.S. The difference between ../../ and ../../../ is just a matter of preference, not anything technical.  Either should work..

**Comment by rasa** [comment]
Yeah, I tested hardcoding both `ARCH=x86` and `ARCH=x86_64`, and `setup-x86_64.exe` has segfaulted several times if run more than once (but not always). `setup-x86.exe` has never crashed for me.

**Comment by rasa** [comment]
On Windows 7x64, for some reason, almost _anything_ works, including: `file://iso`, `file://../iso`, `file://../../iso`, `file://../../../iso`, `iso`, `../iso`, `../../iso`, `../../../iso`. Go figure. Full disclosure: I'm running a slightly hacked version of 0.3.7.

**Comment by misheska** [comment]
Thanks for the update.  I also pushed the relative path changes.  This didn't work with the older version of packer that I was using when I assembled the original windows templates.  Good to see relatives paths work now.

**Comment by rasa** [comment]
I fixed the backspace issue by installing the `termcap` and `terminfo` packages. I will include this in my next pull request. Thanks.

I'm pretty sure these 2 packages should be installed by default. Now, I'm wondering what _else_ hasn't been installed that should be. To determine this, I will install the base cygwin packages using the old (`setup.exe`) installer, and the new one, to see what other packages, if any, need to be installed.

**Comment by misheska** [comment]
Thanks for sorting this out.  I'm sure the community will appreciate all your work to put together some workable Windows templates.

**Pull request closed without merging**
